# Generated by Django 4.1.1 on 2022-09-14 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_active_product_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='active',
        ),
    ]
